=pod

=encoding utf8

=head1 NAME

Mojolicious::Plugin::TextHelpers - Methods to format, count, delimit, etc...

=head1 SYNOPSIS

  # Mojolicious
  $self->plugin('TextHelpers');

  # Mojolicious::Lite
  plugin 'TextHelpers';

  $self->count(10, 'user');     # 10 users
  $self->count([User->new]);    # 1 user
  $self->number('1500.55');     # 1,500.00
  $self->paragraphs($text);     # <p>line 1</p><p>line 2</p>...
  $self->maxwords('a, b, c', 2) # a, b...
  $self->sanitize($html);       # remove all HTML
  $self->sanitize($html, tags => ['a','p']); # keep <p> and <a> tags

=head1 METHODS

=head2 count

    $self->count(10, 'user');           # 10 users
    $self->count([User->new]);          # 1 user
    $self->count([User->new], 'Luser'); # 1 Luser

=head2 maxwords

   $self->maxwords($str, $n);
   $self->maxwords($str, $n, '&hellip;');

Truncate C<$str> after C<$n> words. If C<$str> has more than C<$n> words traling
punctuation characters are stripped from the C<$n>th word and C<'...'> is appended.
An alternate ommision character can be given as the third option.

=head2 number

   $self->number(1500.55); # 1,500.55
   $self->number(1500.55, sep => '.', decimal => ','); # 1.500,55

Format a number.

=head2 paragraphs

    $self->paragraphs($text);

Wrap C<\r\n> delimited text in HTML paragraph tags (C<p>).

=head2 sanitize

    $self->sanitize($html);
    $self->sanitize($html, tags => ['a','p'], attr => ['href']);

Remove all HTML tags in the string given by C<$html>. If C<tags> and/or C<attr>
are given remove everything but those tags and attributes.

=head1 SEE ALSO

L<Mojolicious>, L<Lingua::EN::Inflect>, L<Number::Format>,


=cut

